// .js를 붙여야 함.
import tc1 from './다리를_지나는_트럭.js';
import tc2 from './기능개발.js';
import tc3 from './조이스틱.js';
import tc5 from './스킬트리.js';
import tc6 from './구명보트.js';
import tc7 from './JadenCase_문자열_만들기.js';
import tc8 from './프린터.js';
import tc9 from './카펫.js';
import tc10 from './위장.js';
import tc11 from './방금그곡.js';
import tc12 from './오픈채팅방.js';
import tc13 from './네트워크.js';
import tc15 from './파일명_정렬.js';
// import tc16 from './자물쇠와_열쇠.js';
import tc17 from './Replace_Elements_with_Greatest_Element_on_Right_Side.js';
import tc18 from './Remove_Duplicates_from_Sorted_Array.js';
import tc19 from './Move_Zeros_1.js';
import tc20 from './H-INDEX.js';
import tc21 from './Move_Zeros_1.js';
import tc22 from './가장_먼_노드.js';
import tc23 from './순서.js';
import tc24 from './단어변환.js';

// tc1();
// tc2();
// tc3();
// tc5();
// tc6();
// tc7();
// tc8();
// tc9();
// tc10();
// tc11();
// tc12();
// tc13();
// tc15();
// tc16();
// tc17();
// tc18();
// tc19();
// tc20();
// tc21();
tc22();
tc23();
tc24();
