// .js를 붙여야 함.
import tc1 from './다리를_지나는_트럭.js';
import tc2 from './기능개발.js';
import tc3 from './조이스틱.js';
import tc5 from './스킬트리.js';
import tc6 from './구명보트.js';
import tc7 from './JadenCase_문자열_만들기.js';
import tc8 from './프린터.js';
import tc9 from './카펫.js';
import tc10 from './위장.js';
import tc11 from './방금그곡.js';
import tc12 from './오픈채팅방.js';
import tc13 from './네트워크.js';
import tc14 from './여행경로1.js';
import tc14_2 from './여행경로2.js';
import tc15 from './파일명_정렬.js';
// import tc16 from './자물쇠와_열쇠.js';

// tc1();
// tc2();
// tc3();
// tc5();
// tc6();
// tc7();
// tc8();
// tc9();
// tc10();
// tc11();
// tc12();
// tc13();
tc14();
tc14_2();
tc15();
// tc16();
